version: '3.8'

services:
  postgres:
    container_name: gestao-vagas-postgres
    image: postgres
    ports:
      - 3339:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas